---
- name: Install git
  become: true
  apt:
    name: git

- name: Install python
  become: true
  apt:
    name: "{{ python_app_python_version }}"

- name: Install pip
  become: true
  apt:
    name: "{{ python_app_pip_package }}"

- name: Create directory to hold project
  become: true
  file:
    path: "{{ python_app_project_root | dirname }}"
    state: directory

- name: Update project source code
  become: true
  git:
    depth: 1
    dest: "{{ python_app_project_root }}"
    repo: "{{ python_app_repo }}"
    update: true
    version: "{{ python_app_repo_version }}"

- name: Set permissions on source code
  become: true
  file:
    owner: ubuntu
    path: "{{ python_app_project_root }}"
    recurse: true
    state: directory

- name: Create virtualenv directory
  become: true
  file:
    owner: ubuntu
    path: /opt/venvs
    recurse: true
    state: directory

- name: Install dependencies
  pip:
    requirements: "{{ python_app_project_root }}/requirements.txt"
    virtualenv: /opt/venvs/venv
    virtualenv_python: "{{ python_app_python_version }}"

- name: Save virtualenv location
  set_fact:
    python_app_venv: "/opt/venvs/venv"
